apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: flock-denver

resources:
  - namespace.yaml
  - pvc.yaml
  - deployment.yaml
  - service.yaml
  - cronjob.yaml
  # - ingress.yaml        # enable once you have an ingress controller + host

images:
  - name: flock-denver
    newTag: latest
